services:
  - type: web
    name: cuidapp
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: cd src && gunicorn -w 3 --bind 0.0.0.0:$PORT cuidapp.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
