"""
Django settings for cuidapp project.

Generated by 'django-admin startproject' using Django 6.0.3.
Configurado para producción (Render + Neon + Cloudinary).
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-50c+arbbuyu_xi3kj9^aq(4uxt)yvjt4e4eoox1tomqt)r3tw!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# '*' alcanza para un proyecto de facultad. Si querés más adelante podés
# poner el dominio exacto de Render acá, ej: ['cuidapp.onrender.com']
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'cloudinary_storage',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_apscheduler',
    'rest_framework',
    'cloudinary',
    'rest_framework_simplejwt',
    'corsheaders',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cuidapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.rol_usuario',
                'core.context_processors.notificaciones_tutor',
            ],
        },
    },
]

WSGI_APPLICATION = 'cuidapp.wsgi.application'


# ── Base de datos (Neon / Postgres) ──────────────────────────────────
# 🔴 REEMPLAZÁ esta línea con tu connection string real de Neon.
# La encontrás en el dashboard de Neon → tu proyecto → "Connection string".
# Tiene esta forma: postgresql://usuario:password@ep-algo.neon.tech/neondb?sslmode=require

NEON_DATABASE_URL = 'postgresql://neondb_owner:npg_kuD0Omh5vPcJ@ep-misty-darkness-atf4eo0v.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require'

DATABASES = {
    'default': dj_database_url.parse(
        NEON_DATABASE_URL,
        conn_max_age=600,
        ssl_require=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# ── Archivos estáticos (CSS/JS del panel web) ────────────────────────
# Whitenoise los sirve directo desde Render, sin necesitar otro servicio.

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'core', 'static'),]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

handler404 = 'core.views.error_404'
handler500 = 'core.views.error_500'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

CORS_ALLOW_ALL_ORIGINS = True

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dela6rwit',
    'API_KEY': '753363425638528',
    'API_SECRET': 'DOItTQ2oeAvXGFqIy2Ym9mNLkls',
}

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# dj3-cloudinary-storage (versión vieja) todavía lee esta variable "legacy"
# en vez del diccionario STORAGES de arriba. La dejamos en sincro con
# STORAGES["staticfiles"] para que su comando de collectstatic no explote.
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"