# Generated by Django 6.0.3 on 2026-04-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fotoreceta_medicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
