# Generated by Django 6.0.3 on 2026-04-03 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medicamento_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('doctor', models.CharField(blank=True, max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='core.perfil')),
            ],
        ),
    ]
