# Generated by Django 5.2.6 on 2026-04-03 22:07

import django.db.models.deletion
from django.db import migrations, models


def migrate_usuario_to_perfil(apps, schema_editor):
    cursor = schema_editor.connection.cursor()
    cursor.execute(
        """
        INSERT INTO core_perfil (user_id, rol, tutor_asignado_id)
        SELECT DISTINCT usuario_id, 'tutor', NULL
        FROM core_medicamento
        WHERE usuario_id IS NOT NULL
          AND usuario_id NOT IN (SELECT user_id FROM core_perfil)
        """
    )
    cursor.execute(
        """
        UPDATE core_medicamento
        SET perfil_id = (
            SELECT id FROM core_perfil WHERE core_perfil.user_id = core_medicamento.usuario_id
        )
        WHERE perfil_id IS NULL
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.perfil'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='stock_inicial',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='tomado_hoy',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_usuario_to_perfil, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='medicamento',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perfil'),
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='usuario',
        ),
    ]
