# Generated by Django 6.0.3 on 2026-04-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_migrate_medicamento_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='stock_critico',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='tomas_diarias',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='dosis',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='horario',
            field=models.CharField(default='Horario no definido', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='stock_actual',
            field=models.IntegerField(default=30),
        ),
    ]
