# Generated by Django 6.0.3 on 2026-04-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_medicamento_stock_critico_medicamento_tomas_diarias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='tomas_diarias',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='cada_cuantas_horas',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='horario_fijo',
            field=models.BooleanField(default=True),
        ),
    ]
