# Generated by Django 6.0.3 on 2026-04-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_medicamento_tomas_diarias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('medico', '🩺 Médico/Turno'), ('social', '🎉 Social/Familiar'), ('actividad', '🎨 Taller/Actividad'), ('tramite', '📄 Trámite/Pago'), ('otro', '✨ Otro')], default='medico', max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.perfil')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
    ]
