# Generated by Django 6.0.3 on 2026-04-07 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotoreceta',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tutor_asignado',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='perfil',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='horario',
            new_name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='cada_cuantas_horas',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='horario_fijo',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='stock_critico',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='stock_inicial',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='tomado_hoy',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='stock_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DatoMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('presion', 'Presión Arterial'), ('glucosa', 'Glucosa'), ('peso', 'Peso')], max_length=20)),
                ('valor_1', models.FloatField()),
                ('valor_2', models.FloatField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_mediciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Datos de Mediciones',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='mediciones/fotos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('procesada', models.BooleanField(default=False)),
                ('comentario_ana', models.CharField(blank=True, max_length=255)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fotos de Mediciones',
            },
        ),
        migrations.CreateModel(
            name='PerfilPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=5)),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias Conocidas')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20)),
                ('medico_cabecera', models.CharField(blank=True, max_length=100)),
                ('requiere_control_presion', models.BooleanField(default=False)),
                ('requiere_control_glucosa', models.BooleanField(default=False)),
                ('requiere_control_peso', models.BooleanField(default=False)),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_a_cargo', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_medico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='FotoReceta',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
