# Generated by Django 6.0.3 on 2026-04-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_fotoreceta_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='frecuencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
