# Generated by Django 6.0.5 on 2026-06-03 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_fotomedicion_to_fotodocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='lugar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='tipo',
            field=models.CharField(choices=[('medico', 'Médico / Turno'), ('social', 'Visita / Social'), ('actividad', 'Actividad / Taller'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='fotodocumento',
            name='imagen',
            field=models.ImageField(upload_to='documentos/fotos/'),
        ),
        migrations.AlterField(
            model_name='fotodocumento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_documentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
