# Generated by Django 6.0.5 on 2026-06-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_eventocalendario_lugar_eventocalendario_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpaciente',
            name='numero_afiliado',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Afiliado'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='obra_social',
            field=models.CharField(blank=True, max_length=100, verbose_name='Obra Social'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='plan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Plan'),
        ),
    ]
