# Generated by Django 6.0.5 on 2026-06-04 16:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_perfilpaciente_numero_afiliado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventocalendario',
            options={'ordering': ['fecha_hora']},
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='frecuencia',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='cada_cuantas_horas',
            field=models.IntegerField(default=8, help_text="Solo si frecuencia_tipo='fijo'"),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='dosis_por_toma',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='duracion_tipo',
            field=models.CharField(choices=[('cronico', 'Crónico (todos los días)'), ('temporal', 'Temporal')], default='cronico', max_length=20),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='evento_toma',
            field=models.CharField(blank=True, help_text='Ej: al levantarse, antes de acostarse', max_length=100),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text="Solo si duracion_tipo='temporal'", null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='frecuencia_tipo',
            field=models.CharField(choices=[('fijo', 'Horario Fijo'), ('evento', 'Relativo a Evento')], default='fijo', max_length=20),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='horario_fijo',
            field=models.CharField(blank=True, help_text='Ej: 08:00 hs', max_length=100),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='tipo_presentacion',
            field=models.CharField(choices=[('comprimido', 'Comprimido'), ('gota', 'Gotas'), ('liquido', 'Líquido'), ('inyectable', 'Inyectable'), ('otro', 'Otro')], default='comprimido', max_length=20),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='umbral_stock_minimo',
            field=models.IntegerField(default=5, help_text='Alertar cuando stock <= este valor'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='unidad_medida',
            field=models.CharField(choices=[('unidades', 'Unidades'), ('gotas', 'Gotas'), ('ml', 'ml'), ('mg', 'mg')], default='unidades', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='stock_total',
            field=models.IntegerField(default=0, help_text='Cantidad en cada caja estándar'),
        ),
        migrations.CreateModel(
            name='RegistroToma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('cantidad_tomada', models.FloatField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_toma', to='core.medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_toma', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
