# Generated by Django 6.0.3 on 2026-06-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_eventocalendario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='frecuencia_tipo',
            field=models.CharField(choices=[('fijo', 'Horario Fijo'), ('intervalo', 'Cada X horas'), ('evento', 'Relativo a Evento')], default='fijo', max_length=20),
        ),
    ]
