# Generated by Django 6.0.3 on 2026-06-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_medicamento_frecuencia_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotodocumento',
            name='imagen',
            field=models.FileField(upload_to='documentos/fotos/'),
        ),
    ]
