# Generated by Django 6.0.3 on 2026-06-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_fotodocumento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='cada_cuantas_horas',
            field=models.IntegerField(blank=True, help_text='Ej: 6, 8, 12, 24', null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='evento_toma',
            field=models.CharField(blank=True, help_text='Ej: al levantarse, antes de acostarse', max_length=200),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='horario_fijo',
            field=models.CharField(blank=True, help_text='Ej: 08:00, 14:00, 20:00', max_length=200),
        ),
    ]
