# Generated by Django 6.0.3 on 2026-06-07 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotodocumento',
            name='imagen',
            field=models.FileField(upload_to='documentos/fotos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
