# Generated by Django 6.0.3 on 2026-06-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_medicamento_tipo_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='tipo_presentacion',
            field=models.CharField(choices=[('comprimido', 'Comprimido'), ('gota', 'Gotas'), ('liquido', 'Jarabe o Líquido'), ('inyectable', 'Inyectable')], default='comprimido', max_length=20),
        ),
    ]
