# Generated by Django 6.0.3 on 2026-06-11 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_medicamento_tipo_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datomedicion',
            name='foto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fotodocumento'),
        ),
    ]
