# Generated by Django 6.0.3 on 2026-06-15 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='cada_cuantas_horas',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
