# Generated by Django 6.0.3 on 2026-06-16 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_perfiltutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datomedicion',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fotodocumento'),
        ),
    ]
