# Generated by Django 6.0.3 on 2026-06-16 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_datomedicion_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioToma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.medicamento')),
            ],
            options={
                'verbose_name': 'Horario de Toma',
                'verbose_name_plural': 'Horarios de Toma',
                'ordering': ['hora'],
            },
        ),
    ]
