# Generated by Django 6.0.3 on 2026-06-17 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_horariotoma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilpaciente',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Ingresá un número de teléfono válido. Solo números, espacios, guiones y paréntesis.', regex='^\\+?[\\d\\s\\-\\(\\)]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='perfiltutor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Ingresá un número de teléfono válido. Solo números, espacios, guiones y paréntesis.', regex='^\\+?[\\d\\s\\-\\(\\)]{7,20}$')], verbose_name='Teléfono'),
        ),
    ]
