# Generated by Django 6.0.3 on 2026-06-17 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_perfilpaciente_telefono_emergencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilpaciente',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Formato inválido. Ingresá el símbolo + seguido del código de país y tu número, sin espacios ni guiones (Ej: +5491112345678).', regex='^\\+[1-9]\\d{10,14}$')]),
        ),
        migrations.AlterField(
            model_name='perfiltutor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Formato inválido. Ingresá el símbolo + seguido del código de país y tu número, sin espacios ni guiones (Ej: +5491112345678).', regex='^\\+[1-9]\\d{10,14}$')], verbose_name='Teléfono'),
        ),
    ]
