# Generated by Django 6.0.3 on 2026-06-18 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_perfilpaciente_telefono_emergencia_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatoDispositivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bateria", models.IntegerField()),
                ("tipo_conexion", models.CharField(max_length=50)),
                ("latitud", models.FloatField(blank=True, null=True)),
                ("longitud", models.FloatField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datos_dispositivo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dato de dispositivo",
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
