# Generated by Django 6.0.3 on 2026-06-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_datodispositivo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datodispositivo",
            options={
                "ordering": ["-fecha_registro"],
                "verbose_name": "Dato de Dispositivo",
                "verbose_name_plural": "Datos de Dispositivos",
            },
        ),
        migrations.AlterField(
            model_name="datodispositivo",
            name="bateria",
            field=models.IntegerField(
                default=0, help_text="Porcentaje de batería (0-100)"
            ),
        ),
        migrations.AlterField(
            model_name="datodispositivo",
            name="tipo_conexion",
            field=models.CharField(
                blank=True, help_text="Ej: wifi, 4g, none", max_length=50
            ),
        ),
    ]
