# Generated by Django 6.0.3 on 2026-06-20 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_datodispositivo_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilpaciente",
            name="tutor_emergencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pacientes_emergencia",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Contacto de emergencia",
            ),
        ),
    ]
