# Generated by Django 6.0.3 on 2026-06-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotodocumento',
            name='nota_paciente',
        ),
    ]
