# Generated by Django 6.0.3 on 2026-06-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_remove_fotodocumento_nota_paciente"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotodocumento",
            name="nota_paciente",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
